"""All colors, sizes, and layout offsets used by view/renderer.py -
kept separate so renderer.py itself stays focused on drawing logic."""

# --- Cooldown overlay ("hourglass" over a resting piece) ---
COOLDOWN_OVERLAY_COLOR_BGRA = (235, 206, 135, 120)

# --- Selected-cell border ---
SELECTION_HIGHLIGHT_COLOR_BGRA = (0, 215, 255, 255)
SELECTION_HIGHLIGHT_THICKNESS = 4

# --- Legal-destination fill (green = empty, red = capturable) ---
DESTINATION_HIGHLIGHT_COLOR_BGRA = (60, 200, 60, 130)
CAPTURE_HIGHLIGHT_COLOR_BGRA = (50, 50, 220, 150)

# --- Invalid-target flash border ---
INVALID_TARGET_HIGHLIGHT_COLOR_BGRA = (0, 0, 255, 255)
INVALID_TARGET_HIGHLIGHT_THICKNESS = 4

# --- Game-over overlay ---
GAME_OVER_TEXT = "GAME OVER"
GAME_OVER_TEXT_COLOR_BGRA = (255, 255, 255, 255)
GAME_OVER_FONT_SIZE = 2.0
GAME_OVER_THICKNESS = 4
GAME_OVER_BAND_HEIGHT = 190
GAME_OVER_BAND_COLOR_BGRA = (20, 20, 20, 195)
GAME_OVER_TITLE_OFFSET_Y = 55

# --- Game-over "New Game" button ---
GAME_OVER_BUTTON_WIDTH = 200
GAME_OVER_BUTTON_HEIGHT = 46
GAME_OVER_BUTTON_OFFSET_Y = 118
GAME_OVER_BUTTON_COLOR_BGRA = (70, 70, 70, 255)
GAME_OVER_BUTTON_BORDER_COLOR_BGRA = (255, 255, 255, 255)
GAME_OVER_BUTTON_BORDER_THICKNESS = 2
GAME_OVER_BUTTON_TEXT = "New Game"
GAME_OVER_BUTTON_FONT_SIZE = 0.7
GAME_OVER_BUTTON_TEXT_THICKNESS = 2

# --- Game-over hint line ---
GAME_OVER_HINT_TEXT = "or press ESC to quit"
GAME_OVER_HINT_FONT_SIZE = 0.55
GAME_OVER_HINT_THICKNESS = 1
GAME_OVER_HINT_OFFSET_Y = 165

# --- Side panels (team name, score, move log) ---
SIDE_PANEL_WIDTH = 220  # reference width at the reference CELL_SIZE
SIDE_PANEL_BACKGROUND_COLOR_BGRA = (40, 40, 40, 255)
SIDE_PANEL_TEXT_COLOR_BGRA = (255, 255, 255, 255)
SIDE_PANEL_ACCENT_COLOR_BGRA = (0, 255, 255, 255)
SIDE_PANEL_HEADER_FONT_SIZE = 0.7
SIDE_PANEL_HEADER_THICKNESS = 2
SIDE_PANEL_ROW_FONT_SIZE = 0.5
SIDE_PANEL_ROW_THICKNESS = 1

SIDE_PANEL_TEAM_LABEL_Y = 26
SIDE_PANEL_PLAYER_INFO_Y = 46  # "username (rating)" - and "(You)" for whichever panel is the local player's own
SIDE_PANEL_SCORE_Y = 70
SIDE_PANEL_COLUMNS_Y = 98
SIDE_PANEL_ROWS_START_Y = 120
SIDE_PANEL_ROW_HEIGHT = 20
SIDE_PANEL_PADDING = 12
SIDE_PANEL_MOVE_COLUMN_FRACTION = 0.45
SIDE_PANEL_PLAYER_INFO_FONT_SIZE = 0.45

SIDE_PANEL_DIVIDER_COLOR_BGRA = (90, 90, 90, 255)
SIDE_PANEL_DIVIDER_THICKNESS = 2
